hugoblox:
  schema: "2.0"
  identity:
    name: Yixuan Shao (邵一轩)
    type: person
    tagline: Astronomy | PhD Student
    description: The personal website of Yixuan Shao, a PhD Student at Nanjing Univerisity
  theme:
    mode: system
    pack: default
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: false
    theme_toggle: true
    language_switcher: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: false
